# Generated by Django 4.1.5 on 2023-05-15 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=100)),
                ('CategoryDesc', models.CharField(max_length=100)),
                ('CategoryDateTime', models.DateTimeField(auto_now_add=True)),
                ('DateTimeUpdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StateName', models.CharField(max_length=100)),
                ('StateDesc', models.CharField(max_length=100)),
                ('StateDate', models.DateTimeField(auto_now_add=True)),
                ('StateDateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubCategoryName', models.CharField(max_length=100)),
                ('SubCategoryDateTime', models.DateTimeField(auto_now_add=True)),
                ('UpdateDateTime', models.DateTimeField(auto_now=True)),
                ('InheritCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.category')),
            ],
        ),
    ]
