# Generated by Django 4.1.5 on 2023-05-15 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='UploadedData/Images')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintLodge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=100)),
                ('Desc', models.TextField()),
                ('Doc', models.FileField(upload_to='UploadedData/Files')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.category')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.state')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.subcategory')),
            ],
        ),
    ]
