# Generated by Django 4.2.1 on 2023-07-30 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_image_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='ProfileImage',
        ),
    ]
