# Generated by Django 4.2.1 on 2023-07-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profileimage_user_alter_profileimage_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='user',
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
